require('dotenv').config();
const { Client } = require('pg');

async function main() {
  const client = new Client({
    connectionString: `postgres://postgres:11fit@202612@db.nfubnpgfwgrlpfhcbjlg.supabase.co:5432/postgres`
  });

  try {
    await client.connect();
    
    // Create quick replies table
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.whatsapp_quick_replies (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        label text NOT NULL,
        text text NOT NULL,
        created_at timestamp with time zone DEFAULT now()
      );
    `);
    
    // Add default replies
    await client.query(`
      INSERT INTO public.whatsapp_quick_replies (label, text) VALUES
      ('Returns Portal', 'You can easily process your return or exchange by visiting our website: www.11fit.in/a/returns'),
      ('HR / Careers', 'We handle recruitment via email. Please send your CV to careers@11fit.com'),
      ('Website Link', 'You can check out our latest collection on our website: www.11fit.in')
    `);

    // Update settings table with new policies
    const newBrandPolicy = `- Oversized Tees & Track Pants: Combed cotton & 4-Way Lycra. Size Guide available on our website.
- Shipping: 3-5 business days across India. COD & Prepaid available.
- Returns & Exchanges: 7-Day Return/Exchange policy. Customers must process returns via our website (www.11fit.in) on the returns portal.
- Recruitment/HR: For jobs or CV submissions, strictly tell them to email careers@11fit.com. Do not ask for CVs on WhatsApp.
- Support: For escalations or detailed support, email support@11fit.com.
- Website: www.11fit.in`;

    await client.query(`
      UPDATE public.whatsapp_settings 
      SET inst_brand_policies = $1 
      WHERE id = (SELECT id FROM public.whatsapp_settings ORDER BY id DESC LIMIT 1);
    `, [newBrandPolicy]);

    console.log("Database updated successfully!");
  } catch (err) {
    console.error(err);
  } finally {
    await client.end();
  }
}
main();
